'use strict';
document.documentElement.classList.add('js');
const motionQuery=matchMedia('(prefers-reduced-motion: reduce)');
let paused=motionQuery.matches;
const pauseButton=document.querySelector('#motion-toggle');
function syncMotion(){document.body.classList.toggle('motion-paused',paused);pauseButton.textContent=paused?'Play animation ▷':'Pause animation Ⅱ';pauseButton.setAttribute('aria-pressed',String(paused));}
pauseButton.addEventListener('click',()=>{paused=!paused;syncMotion();});motionQuery.addEventListener('change',e=>{paused=e.matches;syncMotion();});syncMotion();
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target);}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
document.querySelector('#year').textContent=new Date().getFullYear();function clock(){document.querySelector('#clock').textContent=new Date().toLocaleTimeString('en-GB',{timeZone:'Europe/London',hour:'2-digit',minute:'2-digit'});}clock();setInterval(clock,60000);
let active=0;const cards=[...document.querySelectorAll('[data-project]')];function renderProjects(){cards.forEach((card,i)=>{card.dataset.position=i===active?'active':i===(active+1)%3?'right':'left';});document.querySelector('#project-position').textContent=`0${active+1} / 03`;}
document.querySelector('#prev-project').addEventListener('click',()=>{active=(active+2)%3;renderProjects();});document.querySelector('#next-project').addEventListener('click',()=>{active=(active+1)%3;renderProjects();});renderProjects();
const services=['SEO','Web Development'];const cart=new Set();try{const saved=JSON.parse(localStorage.getItem('rizwan-services')||'[]');if(Array.isArray(saved))saved.filter(x=>services.includes(x)).forEach(x=>cart.add(x));}catch{}
const dialog=document.querySelector('#cart-dialog');const items=document.querySelector('#cart-items');let lastFocus;function closeCart(){dialog.close();document.body.style.overflow='';lastFocus?.focus();}function openCart(){lastFocus=document.activeElement;dialog.showModal();document.body.style.overflow='hidden';}document.querySelectorAll('[data-open-cart]').forEach(b=>b.addEventListener('click',openCart));document.querySelector('#close-cart').addEventListener('click',closeCart);dialog.addEventListener('cancel',e=>{e.preventDefault();closeCart();});dialog.addEventListener('click',e=>{if(e.target===dialog&&e.clientX<dialog.getBoundingClientRect().left)closeCart();});
function renderCart(){try{localStorage.setItem('rizwan-services',JSON.stringify([...cart]));}catch{}document.querySelectorAll('[data-count]').forEach(n=>n.textContent=cart.size);items.replaceChildren();if(!cart.size){const p=document.createElement('p');p.className='empty-cart';p.textContent='Your brief is empty. Select SEO, Web Development or both to get started.';items.append(p);const b=document.createElement('button');b.className='pill dark';b.textContent='Choose services';b.onclick=()=>{closeCart();document.querySelector('#services').scrollIntoView({behavior:paused?'instant':'smooth'});};items.append(b);}for(const service of cart){const row=document.createElement('div');row.className='cart-item';const name=document.createElement('strong');name.textContent=service;const remove=document.createElement('button');remove.textContent='Remove';remove.setAttribute('aria-label',`Remove ${service}`);remove.onclick=()=>{cart.delete(service);renderCart();};row.append(name,remove);items.append(row);}document.querySelector('#checkout').disabled=!cart.size;document.querySelectorAll('[data-service]').forEach(b=>{const selected=cart.has(b.dataset.service);b.innerHTML=selected?'Added to brief <span>✓</span>':'Add to brief <span>+</span>';b.setAttribute('aria-pressed',String(selected));});}
let toastTimer;document.querySelectorAll('[data-service]').forEach(b=>b.addEventListener('click',()=>{if(cart.has(b.dataset.service)){openCart();return;}cart.add(b.dataset.service);renderCart();const toast=document.querySelector('#toast');toast.textContent=`${b.dataset.service} added — open “Your brief” to checkout.`;toast.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('visible'),3500);}));renderCart();
function buildWhatsAppUrl(selected,name,website,brief){const message=['Hello Rizwan, I would like to request the following services:',...selected.map(s=>`• ${s}`),name?`\nName: ${name}`:'',website?`Website: ${website}`:'',brief?`\nProject brief: ${brief}`:'','\nPlease let me know the next steps and a quote.'].filter(Boolean).join('\n');return 'https://wa.me/447404303928?text='+encodeURIComponent(message);}
document.querySelector('#checkout-form').addEventListener('submit',e=>{e.preventDefault();if(!cart.size)return;const data=new FormData(e.currentTarget);const url=buildWhatsAppUrl([...cart],data.get('name').trim(),data.get('website').trim(),data.get('brief').trim());window.open(url,'_blank','noopener,noreferrer');});
// Perspective-projected torus: small, dependency-free 3D geometry.
const canvas=document.querySelector('#sculpture'),ctx=canvas.getContext('2d');let angle=0,last=0,heroVisible=true,pointerX=0,pointerY=0;const hero=document.querySelector('.hero');new IntersectionObserver(es=>{heroVisible=es[0].isIntersecting;}).observe(hero);hero.addEventListener('pointermove',e=>{const r=hero.getBoundingClientRect();pointerX=(e.clientX-r.left)/r.width-.5;pointerY=(e.clientY-r.top)/r.height-.5;});hero.addEventListener('pointerleave',()=>{pointerX=0;pointerY=0;});
function draw(){const r=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,1.5);if(canvas.width!==Math.round(r.width*dpr)||canvas.height!==Math.round(r.height*dpr)){canvas.width=Math.round(r.width*dpr);canvas.height=Math.round(r.height*dpr);}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,r.width,r.height);const size=Math.min(r.width,r.height)*.29,points=[];const ax=.7+pointerY*.3,ay=angle+pointerX*.3;for(let i=0;i<70;i++){const u=i/70*Math.PI*2;for(let j=0;j<24;j++){const v=j/24*Math.PI*2;let x=(1+.35*Math.cos(v))*Math.cos(u),y=(1+.35*Math.cos(v))*Math.sin(u),z=.35*Math.sin(v);const y1=y*Math.cos(ax)-z*Math.sin(ax),z1=y*Math.sin(ax)+z*Math.cos(ax);const x2=x*Math.cos(ay)+z1*Math.sin(ay),z2=-x*Math.sin(ay)+z1*Math.cos(ay);const p=3.5/(3.5+z2);points.push({x:r.width*.5+x2*size*p,y:r.height*.5+y1*size*p,z:z2,p});}}points.sort((a,b)=>b.z-a.z);for(const p of points){ctx.fillStyle=`rgba(214,252,57,${.18+(1.4-p.z)/3*.65})`;ctx.beginPath();ctx.arc(p.x,p.y,Math.max(.7,1.55*p.p),0,Math.PI*2);ctx.fill();}}
function frame(t){if(t-last>33){if(heroVisible&&!document.hidden){if(!paused)angle+=.007;if(!paused||last===0)draw();}last=t;}requestAnimationFrame(frame);}if(ctx){draw();requestAnimationFrame(frame);window.addEventListener('resize',draw);}
